/*
 * Created on 2022-11-27 ( Time 20:38:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

package com.apptmyz.fpgreetings.repository;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;

import com.apptmyz.fpgreetings.entity.SecretSantaData ;



/**
 * Spring JPA Repository for SecretSantaData
 * 
 * @author Telosys Tools Generator
 *
 */
public interface SecretSantaDataRepository extends CrudRepository<SecretSantaData, Integer> {

	@Query(nativeQuery = true, value = " SELECT ss.from_email, ss.secret_santa_email, ss.gift_year, sg.flag, sg.gift_item_type, sg.address1, sg.address2, sg.pincode, sg.mobile_number "
			+ " FROM greetings.secret_santa_data ss left join greetings.secret_santa_gift_address_data sg on (ss.secret_santa_email= sg.email and ss.gift_year = sg.gift_year) "
			+ " where ss.from_email = ?1 and ss.gift_year = ?2 ")
	List<Object[]> getSecretSantaCurrentYearDetails(String emailId, String year);
}