/*
 * Created on 11 Oct 2022 ( Time 22:31:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.apptmyz.fpgreetings.repository;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;

import com.apptmyz.fpgreetings.entity.UserRegistrationData;

/**
 * Spring JPA Repository for UserRegistrationData
 * 
 * @author Telosys Tools Generator
 *
 */
public interface UserRegistrationDataRepository extends CrudRepository<UserRegistrationData, Integer> {

	UserRegistrationData findByEmailAndActiveFlag(String mailId, int activeFlag);
	
	UserRegistrationData findById(Integer id);
	
	@Query(nativeQuery = true, value = "SELECT * FROM greetings.user_registration_data where email = ?1 and active_flag = ?2 and date_format(dob, '%d%m') = ?3")
	UserRegistrationData getByEmailAndActiveFlagAndDob(String mailId, int activeFlag, String ddMM);
}