/*
 * Created on 11 Oct 2022 ( Time 22:31:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.apptmyz.fpgreetings.repository;

import java.util.Date;
import java.util.List;

import org.springframework.data.repository.CrudRepository;

import com.apptmyz.fpgreetings.entity.WishesData;

/**
 * Spring JPA Repository for WishesData
 * 
 * @author Telosys Tools Generator
 *
 */
public interface WishesDataRepository extends CrudRepository<WishesData, Integer> {

	WishesData findByUserRegIdAndToEmailAndBdayDateAndActiveFlag(Integer userRegId, String toMailId, Date dob, int activeFlag);
	
	List<WishesData> findByToEmailAndBdayDateAndActiveFlag(String toMailId, Date dob, int activeFlag);
}
