/*
 * Created on 2022-11-27 ( Time 20:38:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.apptmyz.fpgreetings.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "secret_santa_gift_address_data"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="secret_santa_gift_address_data", catalog="greetings" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SecretSantaGiftAddressData.countAll", query="SELECT COUNT(x) FROM SecretSantaGiftAddressData x" )
} )
public class SecretSantaGiftAddressData implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="email", length=150)
    private String     email        ;

    @Column(name="flag")
    private Integer    flag         ;

    @Column(name="gift_item_type", length=150)
    private String     giftItemType ;

    @Column(name="address1", length=150)
    private String     address1     ;

    @Column(name="address2", length=150)
    private String     address2     ;

    @Column(name="pincode", length=10)
    private String     pincode      ;

    @Column(name="mobile_number", length=15)
    private String     mobileNumber ;

    @Column(name="gift_year", length=10)
    private String       giftYear     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_timestamp")
    private Date       createdTimestamp ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SecretSantaGiftAddressData()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : email ( VARCHAR ) 
    public void setEmail( String email )
    {
        this.email = email;
    }
    public String getEmail()
    {
        return this.email;
    }

    //--- DATABASE MAPPING : flag ( INT ) 
    public void setFlag( Integer flag )
    {
        this.flag = flag;
    }
    public Integer getFlag()
    {
        return this.flag;
    }

    //--- DATABASE MAPPING : gift_item_type ( VARCHAR ) 
    public void setGiftItemType( String giftItemType )
    {
        this.giftItemType = giftItemType;
    }
    public String getGiftItemType()
    {
        return this.giftItemType;
    }

    //--- DATABASE MAPPING : address1 ( VARCHAR ) 
    public void setAddress1( String address1 )
    {
        this.address1 = address1;
    }
    public String getAddress1()
    {
        return this.address1;
    }

    //--- DATABASE MAPPING : address2 ( VARCHAR ) 
    public void setAddress2( String address2 )
    {
        this.address2 = address2;
    }
    public String getAddress2()
    {
        return this.address2;
    }

    //--- DATABASE MAPPING : pincode ( VARCHAR ) 
    public void setPincode( String pincode )
    {
        this.pincode = pincode;
    }
    public String getPincode()
    {
        return this.pincode;
    }

    //--- DATABASE MAPPING : mobile_number ( VARCHAR ) 
    public void setMobileNumber( String mobileNumber )
    {
        this.mobileNumber = mobileNumber;
    }
    public String getMobileNumber()
    {
        return this.mobileNumber;
    }

    //--- DATABASE MAPPING : gift_year ( DATE ) 
    public void setGiftYear( String giftYear )
    {
        this.giftYear = giftYear;
    }
    public String getGiftYear()
    {
        return this.giftYear;
    }
    
    //--- DATABASE MAPPING : created_timestamp ( DATETIME ) 
    public void setCreatedTimestamp( Date createdTimestamp )
    {
        this.createdTimestamp = createdTimestamp;
    }
    public Date getCreatedTimestamp()
    {
        return this.createdTimestamp;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(email);
        sb.append("|");
        sb.append(flag);
        sb.append("|");
        sb.append(giftItemType);
        sb.append("|");
        sb.append(address1);
        sb.append("|");
        sb.append(address2);
        sb.append("|");
        sb.append(pincode);
        sb.append("|");
        sb.append(mobileNumber);
        sb.append("|");
        sb.append(giftYear);
        sb.append("|");
        sb.append(createdTimestamp);
        return sb.toString(); 
    } 

}