/*
 * Created on 2022-11-27 ( Time 20:38:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.apptmyz.fpgreetings.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "secret_santa_data"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="secret_santa_data", catalog="greetings" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SecretSantaData.countAll", query="SELECT COUNT(x) FROM SecretSantaData x" )
} )
public class SecretSantaData implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="from_email", length=150)
    private String     fromEmail    ;

    @Column(name="secret_santa_email", length=250)
    private String     secretSantaEmail ;

    @Column(name="gift_year", length=10)
    private String       giftYear     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_timestamp")
    private Date       createdTimestamp ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SecretSantaData()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : from_email ( VARCHAR ) 
    public void setFromEmail( String fromEmail )
    {
        this.fromEmail = fromEmail;
    }
    public String getFromEmail()
    {
        return this.fromEmail;
    }

    //--- DATABASE MAPPING : secret_santa_email ( VARCHAR ) 
    public void setSecretSantaEmail( String secretSantaEmail )
    {
        this.secretSantaEmail = secretSantaEmail;
    }
    public String getSecretSantaEmail()
    {
        return this.secretSantaEmail;
    }

    //--- DATABASE MAPPING : gift_year ( DATE ) 
    public void setGiftYear( String giftYear )
    {
        this.giftYear = giftYear;
    }
    public String getGiftYear()
    {
        return this.giftYear;
    }

    //--- DATABASE MAPPING : created_timestamp ( DATETIME ) 
    public void setCreatedTimestamp( Date createdTimestamp )
    {
        this.createdTimestamp = createdTimestamp;
    }
    public Date getCreatedTimestamp()
    {
        return this.createdTimestamp;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(fromEmail);
        sb.append("|");
        sb.append(secretSantaEmail);
        sb.append("|");
        sb.append(giftYear);
        sb.append("|");
        sb.append(createdTimestamp);
        return sb.toString(); 
    } 

}